[political_democracy]
git-tree-sha1 = "a02b07e3523570d8a27c9fe10dcac3a1e4705c33"
lazy = true

    [[political_democracy.download]]
    sha256 = "1ff834ddeea66c606c8c52bff604c2f18fda3a0e1e91ac41df069178cb7a5802"
    url = "https://github.com/StructuralEquationModels/Data/raw/main/datasets/political_democracy/compressed/data.csv.tar.gz"
